### ISSUE TITLE
Incompatable with TypeScript 4.9

### ISSUE THREAD

**Issue by cjbarth** [node-saml/node-saml#218]
When using `typescript@4.9`, the following error appears, which doesn't exist on `typescript@4.8`:

> TSError: ⨯ Unable to compile TypeScript:
> src/inmemory-cache-provider.ts:25:50 - error TS2304: Cannot find name 'this'.
> 
> 25   private removeKeyIfExpired: (key: keyof typeof this.cacheKeys, nowMs: number) => Promise<void>;

**Comment by markstos** [comment]
@cjbarth Would this issue be resolved with TypeScript 5?

**Comment by cjbarth** [comment]
I intend to do testing to figure that out. If it isn't resolved, we may need to adjust our code to work here.

**Comment by cjbarth** [comment]
After moving to TypeScript 5.x, this problem went away.
